source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MagneticFields_Example' do
  pod "MagneticFields", :path => "../"
end

target 'MagneticFields_Tests' do
  pod "MagneticFields", :path => "../"

  
end
